# Generated by Django 5.2.17 on 2026-08-28 18:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(db_index=True, max_length=150)),
                ('model_version', models.CharField(default='1.0.0', max_length=50)),
                ('latency_ms', models.FloatField(default=0.0)),
                ('input_payload', models.JSONField(blank=True, default=dict)),
                ('output_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('confidence_score', models.FloatField(default=0.85)),
                ('requires_human_review', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='cases.case')),
                ('interaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='interactions.interaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIAuditResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_confidence', models.FloatField(default=0.85)),
                ('disagreement_score', models.FloatField(default=0.0)),
                ('has_cross_modal_conflict', models.BooleanField(default=False)),
                ('requires_human_review', models.BooleanField(default=False)),
                ('audit_flags', models.JSONField(blank=True, default=list)),
                ('reasoning', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audit_result', to='ai_analysis.aianalysis')),
            ],
        ),
        migrations.CreateModel(
            name='DistressAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('distress_score', models.IntegerField(default=30)),
                ('sentiment_score', models.IntegerField(default=0)),
                ('sentiment_label', models.CharField(default='Neutral', max_length=50)),
                ('threat_detected', models.BooleanField(default=False)),
                ('threat_keywords', models.JSONField(blank=True, default=list)),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='distress_assessment', to='ai_analysis.aianalysis')),
            ],
        ),
        migrations.CreateModel(
            name='EmotionAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('primary_emotion', models.CharField(default='Neutral', max_length=50)),
                ('intensity', models.FloatField(default=0.8)),
                ('emotion_breakdown', models.JSONField(blank=True, default=dict)),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emotion_assessment', to='ai_analysis.aianalysis')),
            ],
        ),
        migrations.CreateModel(
            name='VoiceStressAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voice_stress_score', models.IntegerField(default=30)),
                ('voice_stress_level', models.CharField(default='Normal', max_length=50)),
                ('acoustic_features', models.JSONField(blank=True, default=dict)),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voice_stress_assessment', to='ai_analysis.aianalysis')),
            ],
        ),
    ]
