# Generated by Django 5.2.17 on 2026-08-28 18:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributingFactorItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('factor', models.CharField(max_length=200)),
                ('points', models.IntegerField(default=10)),
                ('category', models.CharField(default='Trend', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributing_factors', to='cases.case')),
            ],
            options={
                'ordering': ['-points'],
            },
        ),
        migrations.CreateModel(
            name='LongitudinalMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recorded_date', models.DateField()),
                ('week_label', models.CharField(default='Week 1', max_length=50)),
                ('distress_score', models.IntegerField(default=35)),
                ('engagement_score', models.IntegerField(default=85)),
                ('sentiment_score', models.IntegerField(default=0)),
                ('threat_signal_score', models.IntegerField(default=10)),
                ('check_in_frequency', models.IntegerField(default=4)),
                ('case_stage', models.CharField(default='Investigation', max_length=50)),
                ('detected_signal', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='longitudinal_metrics', to='cases.case')),
                ('interaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='interactions.interaction')),
            ],
            options={
                'ordering': ['recorded_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonalBaseline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('baseline_score', models.FloatField(default=35.0)),
                ('sample_count', models.IntegerField(default=1)),
                ('established_date', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_baseline', to='cases.case')),
            ],
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_level', models.CharField(choices=[('LOW', 'LOW'), ('MODERATE', 'MODERATE'), ('HIGH', 'HIGH'), ('CRITICAL', 'CRITICAL')], max_length=20)),
                ('previous_level', models.CharField(choices=[('LOW', 'LOW'), ('MODERATE', 'MODERATE'), ('HIGH', 'HIGH'), ('CRITICAL', 'CRITICAL')], max_length=20)),
                ('distress_score', models.IntegerField()),
                ('primary_factor', models.TextField()),
                ('ai_summary', models.TextField()),
                ('confidence', models.FloatField(default=0.85)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments', to='cases.case')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
