# Generated by Django 5.2.17 on 2026-08-28 18:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(choices=[('POLICE', 'State Police (CCTNS / ICJS)'), ('COURT', 'Special Court (eCourts / CIS)'), ('SOCIAL_JUSTICE', 'Social Justice & Empowerment Department'), ('HEALTH', 'District Health & Civil Hospital'), ('LEGAL_AID', 'District Legal Services Authority (DLSA)'), ('WITNESS_PROTECTION', 'District Witness Protection Committee')], max_length=50, unique=True)),
                ('api_endpoint', models.URLField(blank=True, default='https://api.gov.in/icjs/mock')),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(auto_now=True)),
                ('sync_status', models.CharField(default='ONLINE', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='IntegrationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('external_reference', models.CharField(blank=True, default='', max_length=100)),
                ('summary', models.CharField(max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_events', to='cases.case')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='integrations.departmentintegration')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
