# Generated by Django 5.2.17 on 2026-08-28 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Counselling', 'Counselling'), ('Medical Treatment', 'Medical Treatment'), ('Witness Protection', 'Witness Protection'), ('Relocation Support', 'Relocation Support'), ('Financial Assistance', 'Financial Assistance'), ('Legal Aid', 'Legal Aid'), ('Rehabilitation', 'Rehabilitation')], db_index=True, default='Counselling', max_length=50)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Escalated', 'Escalated')], db_index=True, default='Pending', max_length=30)),
                ('priority', models.CharField(choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3')], default='P2', max_length=10)),
                ('assigned_to_name', models.CharField(blank=True, default='Dr. Sunita Deshmukh', max_length=150)),
                ('department', models.CharField(default='District Legal Services Authority (DLSA)', max_length=150)),
                ('target_date', models.CharField(blank=True, default='2026-09-05', max_length=50)),
                ('completed_date', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_interventions', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='cases.case')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
