version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: saathi_postgres
    environment:
      POSTGRES_DB: saathi_db
      POSTGRES_USER: saathi_user
      POSTGRES_PASSWORD: saathi_secure_pass_2026
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U saathi_user -d saathi_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: saathi_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: saathi_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=saathi-super-secret-dev-key-change-in-production-2026-poa-secure
      - DEBUG=True
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=saathi_db
      - DB_USER=saathi_user
      - DB_PASSWORD=saathi_secure_pass_2026
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - AI_MODE=mock
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  celery_worker:
    build: .
    container_name: saathi_celery_worker
    command: celery -A config worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - SECRET_KEY=saathi-super-secret-dev-key-change-in-production-2026-poa-secure
      - DEBUG=True
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=saathi_db
      - DB_USER=saathi_user
      - DB_PASSWORD=saathi_secure_pass_2026
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - AI_MODE=mock
    depends_on:
      backend:
        condition: service_started
      redis:
        condition: service_healthy

volumes:
  postgres_data:
  redis_data:
