# Generated by Django 5.2.17 on 2026-08-28 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('Chatbot', 'Chatbot'), ('IVRS', 'IVRS Callback'), ('SMS', 'SMS Pulse'), ('Mobile App', 'Mobile App'), ('Web Portal', 'Web Portal'), ('Toll-Free Helpline', 'Toll-Free Helpline')], db_index=True, default='Chatbot', max_length=40)),
                ('direction', models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound')], default='INBOUND', max_length=20)),
                ('prompt_message', models.TextField(blank=True, default='')),
                ('response_text', models.TextField(blank=True, default='')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='interactions/audio/%Y/%m/')),
                ('audio_duration_seconds', models.FloatField(default=0.0)),
                ('language', models.CharField(default='en', max_length=20)),
                ('processing_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('sentiment_label', models.CharField(default='Neutral', max_length=40)),
                ('threat_detected', models.BooleanField(default=False)),
                ('threat_keywords', models.JSONField(blank=True, default=list)),
                ('voice_stress_score', models.IntegerField(default=30)),
                ('voice_stress_level', models.CharField(default='Normal', max_length=30)),
                ('distress_delta', models.CharField(default='+0', max_length=30)),
                ('ai_signals', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='cases.case')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
