# Generated by Django 5.2.17 on 2026-08-28 18:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('case_type', models.CharField(choices=[('Caste-based Violence', 'Caste-based Violence'), ('Atrocities against SC/ST', 'Atrocities against SC/ST'), ('Witness Intimidation', 'Witness Intimidation'), ('Sexual Assault / Rape', 'Sexual Assault / Rape'), ('Physical Assault', 'Physical Assault'), ('Social Boycott', 'Social Boycott'), ('Land Dispossession', 'Land Dispossession'), ('Hate Crime / Verbal Abuse', 'Hate Crime / Verbal Abuse')], db_index=True, default='Atrocities against SC/ST', max_length=60)),
                ('current_stage', models.CharField(choices=[('Complaint', 'Complaint'), ('Investigation', 'Investigation'), ('Trial', 'Trial'), ('Judgment', 'Judgment'), ('Compensation', 'Compensation'), ('Rehabilitation', 'Rehabilitation'), ('Closure', 'Closure')], db_index=True, default='Investigation', max_length=30)),
                ('distress_score', models.IntegerField(default=35, help_text='Current composite score (0-100)')),
                ('previous_distress_score', models.IntegerField(default=35, help_text='Distress score 7 days prior')),
                ('baseline_score', models.IntegerField(default=35, help_text='Personal historical baseline')),
                ('risk_level', models.CharField(choices=[('LOW', 'LOW'), ('MODERATE', 'MODERATE'), ('HIGH', 'HIGH'), ('CRITICAL', 'CRITICAL')], db_index=True, default='LOW', max_length=20)),
                ('trend_direction', models.CharField(choices=[('increasing', 'increasing'), ('stable', 'stable'), ('decreasing', 'decreasing')], default='stable', max_length=20)),
                ('trend_delta', models.CharField(default='→ 0 (7d)', max_length=50)),
                ('monitoring_status', models.CharField(choices=[('Active', 'Active'), ('Elevated', 'Elevated'), ('Under Review', 'Under Review'), ('Dormant', 'Dormant')], default='Active', max_length=30)),
                ('priority', models.CharField(choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3')], default='P2', max_length=10)),
                ('counsellor_phone', models.CharField(blank=True, default='+91 98230 44102', max_length=30)),
                ('fir_number', models.CharField(blank=True, default='', max_length=100)),
                ('police_station', models.CharField(blank=True, default='', max_length=100)),
                ('special_court', models.CharField(blank=True, default='', max_length=150)),
                ('text_sentiment', models.CharField(default='Neutral', max_length=40)),
                ('distress_language_status', models.CharField(default='Normal', max_length=40)),
                ('voice_stress_status', models.CharField(default='Normal', max_length=40)),
                ('emotion_signal', models.CharField(default='Calm', max_length=40)),
                ('engagement_rate_change', models.CharField(default='0%', max_length=30)),
                ('missed_follow_ups', models.IntegerField(default=0)),
                ('response_frequency', models.CharField(default='Active', max_length=40)),
                ('primary_contributing_factor', models.TextField(blank=True, default='')),
                ('ai_explanation_summary', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_counsellor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='accounts.district')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='accounts.state')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, default='')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical'), ('success', 'Success')], default='info', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='cases.case')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('Complaint', 'Complaint'), ('Investigation', 'Investigation'), ('Trial', 'Trial'), ('Judgment', 'Judgment'), ('Compensation', 'Compensation'), ('Rehabilitation', 'Rehabilitation'), ('Closure', 'Closure')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=50)),
                ('completed', models.BooleanField(default=False)),
                ('is_current', models.BooleanField(default=False)),
                ('distress_trend', models.CharField(blank=True, default='', max_length=100)),
                ('interventions', models.JSONField(blank=True, default=list)),
                ('important_events', models.JSONField(blank=True, default=list)),
                ('order', models.IntegerField(default=0)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='cases.case')),
            ],
            options={
                'ordering': ['order', 'date'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anonymous_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('role', models.CharField(choices=[('Victim', 'Victim'), ('Witness', 'Witness'), ('Family Member', 'Family Member')], default='Victim', max_length=30)),
                ('masked_contact', models.CharField(blank=True, default='•••• •••• 4819', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='cases.subject'),
        ),
    ]
